import { SimulationCategory, Achievement } from "./types";

export const CATEGORIES: SimulationCategory[] = [
  {
    id: "football-owner",
    name: "Football Club Owner",
    description: "Take control of a struggling club, manage budgets, satisfy passionate fans, purchase star players, and lead your squad to the cup championship.",
    iconName: "Users",
    themeColor: "emerald",
    bgGradient: "from-emerald-950/50 to-slate-950",
    tags: ["Sports", "Management", "Strategy"],
    suggestedSearch: "current football transfers, club financial challenges, player values in 2026",
    defaultObjective: "Win the League Cup and secure financial stability within 15 turns.",
  },
  {
    id: "startup-founder",
    name: "Tech Startup Founder",
    description: "Launch an AI tech startup in Silicon Valley. Hire key engineers, raise venture capital, ship innovative features, and guide your company to a legendary IPO.",
    iconName: "Zap",
    themeColor: "sky",
    bgGradient: "from-sky-950/50 to-slate-950",
    tags: ["Business", "Tech", "Finance"],
    suggestedSearch: "latest generative AI trends, Silicon Valley startup valuations, market trends in 2026",
    defaultObjective: "Reach a $100M valuation and secure a series B funding round.",
  },
  {
    id: "zombie-survival",
    name: "Zombie Shelter Coordinator",
    description: "Lead a small community of survivors in a post-apocalyptic bunker. Ration canned goods, salvage weapons, reinforce defenses, and survive toxic waves.",
    iconName: "Flame",
    themeColor: "red",
    bgGradient: "from-red-950/50 to-slate-950",
    tags: ["Survival", "Sci-Fi", "Resource Management"],
    suggestedSearch: "apocalypse survival dynamics, shelter management guidelines",
    defaultObjective: "Survive for 15 days while keeping shelter infection rates below 30%.",
  },
  {
    id: "prime-minister",
    name: "Prime Minister",
    description: "Govern a sovereign country. Pass national budgets, draft social welfare reforms, manage international crises, and navigate public opinion for reelection.",
    iconName: "Shield",
    themeColor: "indigo",
    bgGradient: "from-indigo-950/50 to-slate-950",
    tags: ["Politics", "Diplomacy", "Economy"],
    suggestedSearch: "global GDP growth projections, inflation rates, sovereign fiscal challenges in 2026",
    defaultObjective: "Maintain a public approval rating above 55% and stimulate 4% GDP growth.",
  },
  {
    id: "space-colony",
    name: "Mars Colony Director",
    description: "Establish humanity's first self-sustaining colony on Mars. Balance fragile oxygen reserves, harvest rare minerals, and protect colonists from solar winds.",
    iconName: "Globe",
    themeColor: "purple",
    bgGradient: "from-purple-950/50 to-slate-950",
    tags: ["Sci-Fi", "Space", "Base Building"],
    suggestedSearch: "Mars atmospheric pressures, lunar mining plans, asteroid belt resources",
    defaultObjective: "Establish a fully self-reliant dome colony with 1,000 active citizens.",
  },
  {
    id: "noir-detective",
    name: "Noir Detective",
    description: "Investigate a high-profile corporate murder conspiracy in a rain-slicked metropolis. Search crime scenes, interrogate shady suspects, and deliver justice.",
    iconName: "Eye",
    themeColor: "amber",
    bgGradient: "from-amber-950/40 to-slate-950",
    tags: ["Mystery", "RPG", "Crime"],
    suggestedSearch: "noir detective files, classic crime investigative techniques",
    defaultObjective: "Unmask the true killer of the city mayor before your leads run dry.",
  },
  {
    id: "mafia-boss",
    name: "Mafia Syndicate Boss",
    description: "Build an underground syndicate. Extort rival businesses, run covert smuggles, control territorial turf, and enforce absolute loyalty inside the family.",
    iconName: "Key",
    themeColor: "zinc",
    bgGradient: "from-zinc-900 to-slate-950",
    tags: ["Crime", "Strategy", "Roleplay"],
    suggestedSearch: "syndicate economics, modern federal defense guidelines",
    defaultObjective: "Achieve undisputed control over the city's 5 major districts.",
  },
  {
    id: "restaurant-empire",
    name: "Restaurant Empire Builder",
    description: "Start as a local coffee bistro and build a legendary global culinary empire. Perfect elite recipes, hire star chefs, and secure a perfect 3-star rating.",
    iconName: "Coffee",
    themeColor: "orange",
    bgGradient: "from-orange-950/40 to-slate-950",
    tags: ["Business", "Casual", "Logistics"],
    suggestedSearch: "latest Michelin guide standards, inflation food supply costs in 2026",
    defaultObjective: "Expand to 10 international locations and earn a 3-star culinary rating.",
  },
  {
    id: "f1-principal",
    name: "Formula 1 Team Principal",
    description: "Coordinate split-second mid-race pit stop strategies, optimize aerodynamic engineering, negotiate driver salaries, and dominate the World Constructor Cup.",
    iconName: "Trophy",
    themeColor: "rose",
    bgGradient: "from-rose-950/40 to-slate-950",
    tags: ["Motorsports", "Management", "High-Stakes"],
    suggestedSearch: "Formula 1 aerodynamics, racing strategies, current team standings",
    defaultObjective: "Win the Constructor Championship and balance the team budget.",
  },
  {
    id: "military-commander",
    name: "World War Commander",
    description: "Lead army brigades on dynamic strategic battlefronts. Organize crucial supply networks, utilize tactical air superiority, and outmaneuver enemy garrisons.",
    iconName: "Compass",
    themeColor: "lime",
    bgGradient: "from-lime-950/30 to-slate-950",
    tags: ["Military", "History", "Tactical"],
    suggestedSearch: "historical battle lines, tactical supply line principles",
    defaultObjective: "Successfully secure the disputed coastal sector without massive casualties.",
  },
  {
    id: "day-trader",
    name: "Stock Day Trader",
    description: "Enter the volatile global stock exchanges with a modest cash pile. Leverage options, parse market-moving news, handle margin calls, and outperform the index.",
    iconName: "TrendingUp",
    themeColor: "cyan",
    bgGradient: "from-cyan-950/40 to-slate-950",
    tags: ["Finance", "High-Stakes", "Trading"],
    suggestedSearch: "current stock index trends, hot option volumes, tech stock news in 2026",
    defaultObjective: "Turn $10,000 starting cash into $1,000,000 without hitting a margin liquidation.",
  },
  {
    id: "airline-ceo",
    name: "Global Airline CEO",
    description: "Found an international airline. Route flights, purchase modern fuel-efficient aircraft fleets, manage pilot labor unions, and withstand volatile fuel price spikes.",
    iconName: "Activity",
    themeColor: "blue",
    bgGradient: "from-blue-950/40 to-slate-950",
    tags: ["Logistics", "Business", "Aviation"],
    suggestedSearch: "aviation route statistics, global jet fuel prices 2026",
    defaultObjective: "Operate a 25-plane fleet profitably while keeping flight safety at 100%.",
  }
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "first_million",
    title: "First Million",
    description: "Accumulate at least $1,000,000 or the category equivalent in total wealth.",
    iconName: "DollarSign"
  },
  {
    id: "perfect_ending",
    title: "Perfect Ending",
    description: "Successfully complete any simulation campaign with maximum reputation or rating.",
    iconName: "Award"
  },
  {
    id: "survivor_legend",
    title: "Survivor Legend",
    description: "Complete a survival-based simulator on Hard or Legendary difficulty.",
    iconName: "Flame"
  },
  {
    id: "world_champion",
    title: "World Champion",
    description: "Lead your sport team or racing crew to undisputed championship victory.",
    iconName: "Trophy"
  },
  {
    id: "best_ceo",
    title: "Legendary Business Leader",
    description: "Scale a startup valuation to over $150 Million or reach international IPO status.",
    iconName: "Zap"
  },
  {
    id: "crisis_solver",
    title: "Sovereign Savior",
    description: "Resolve an active, category-specific national emergency or toxic bunker breach.",
    iconName: "Shield"
  }
];
